package com.springboot.api.model;

// Generated Feb 5, 2013 5:52:11 PM by Hibernate Tools 3.4.0.CR1

/**
 * AlmProductos generated by hbm2java
 */
public class RegistryModel implements java.io.Serializable {

	private double dolar;
	private double euro;
	private String formato;

	public RegistryModel() {
	}

	public RegistryModel(double Pdolar,double Peuro ,String formato) {
		this.dolar = Pdolar;
		this.euro = Peuro;
		this.formato = formato;
	}

    public double getDolar() {
        return dolar;
    }

    public void setDolar(double dolar) {
        this.dolar = dolar;
    }

    public double getEuro() {
        return euro;
    }

    public void setEuro(double euro) {
        this.euro = euro;
    }

    public String getFormato() {
        return formato;
    }

    public void setFormato(String formato) {
        this.formato = formato;
    }

	

}
